---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: mozalert-controller
  namespace: mozalert-prod
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: glob:main-*
spec:
  releaseName: mozalert-controller
  chart:
    git: https://github.com/mozilla-it/helm-charts
    ref: main
    path: charts/mozalert-controller
    version: 0.3.0
  values:
    image:
      repository: gcr.io/mozilla-it-service-engineering/github.com/mozilla-it/mozalert
      tag: main-bc3f35eebe4ee04afa7d83787f086324f37d8051
    secretRef: mozalert-secrets
